import sys
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QLineEdit, QLabel, QPlainTextEdit, QAction
from PyQt5.QtGui import QIcon, QFont
from PyQt5.QtCore import pyqtSlot, QCoreApplication

class Ui_MainWindow(object):
    
    def setupUi(self, windowMain):
        windowMain.setGeometry(100, 100, 1200, 800)
        self.button_step = QPushButton(windowMain)
        self.button_step.setGeometry(50,50,150,60)
        self.button_step.setText("Шаг игры")
        self.button_contract = QPushButton(windowMain)
        self.button_contract.setGeometry(250,50,150,60)
        self.button_contract.setText("Конец игры")
        self.button_exit = QPushButton(windowMain)
        self.button_exit.setGeometry(450,50,150,60)
        self.button_exit.setText("Выход")
        self.button_exit.clicked.connect(QCoreApplication.instance().quit)
        self.label_parametrs = QLabel(windowMain)
        self.label_parametrs.setText('Параметры игры')
        self.label_parametrs.setFont(QFont("Times", 14, QFont.Bold))
        self.label_parametrs.move(800,50)
        self.label_parametrs.adjustSize()
        self.label_total_capital = QLabel(windowMain)
        self.label_total_capital.setText('Статистика')
        self.label_total_capital.setFont(QFont("Times", 14, QFont.Bold))
        self.label_total_capital.move(100,180)
        self.label_total_capital.adjustSize()       
        self.plainText = QPlainTextEdit(windowMain)
        self.plainText.setGeometry(50,250,600,500)
        self.plainText.setReadOnly(True)
        #self.plainText.setPlainText("This is some text for our plaintextedit")
        self.label_contract = QLabel(windowMain)
        self.label_contract.setText('Контракт')
        self.label_contract.setFont(QFont("Times", 12, QFont.Bold))
        self.label_contract.setGeometry(850,390,150,60)
        self.label_remaining_period = QLabel(windowMain)
        self.label_remaining_period.setText('Срок')
        self.label_remaining_period.setFont(QFont("Times", 10, QFont.Bold))
        self.label_remaining_period.move(750,450)
        self.label_remaining_period.adjustSize()
        self.textbox_remaining_period = QLineEdit(windowMain)
        self.textbox_remaining_period.setGeometry(1000,450,120,40)
        self.textbox_remaining_period.setText("0")
        self.label_sold_animals_number = QLabel(windowMain)
        self.label_sold_animals_number.setText('Количество животных \n (продажа)')
        self.label_sold_animals_number.setFont(QFont("Times", 10, QFont.Bold))
        self.label_sold_animals_number.move(750,510)
        self.label_sold_animals_number.adjustSize()
        self.textbox_sold_animals_number_young = QLineEdit(windowMain)
        self.textbox_sold_animals_number_young.setGeometry(1000,510,50,40)
        self.textbox_sold_animals_number_young.setText("0")
        self.textbox_sold_animals_number_adult = QLineEdit(windowMain)
        self.textbox_sold_animals_number_adult.setGeometry(1060,510,50,40)
        self.textbox_sold_animals_number_adult.setText("0")
        self.textbox_sold_animals_number_old = QLineEdit(windowMain)
        self.textbox_sold_animals_number_old.setGeometry(1120,510,50,40)
        self.textbox_sold_animals_number_old.setText("0")
        self.label_sold_animals_price = QLabel(windowMain)
        self.label_sold_animals_price.setText('Цена животных \n (продажа)')
        self.label_sold_animals_price.setFont(QFont("Times", 10, QFont.Bold))
        self.label_sold_animals_price.move(750,570)
        self.label_sold_animals_price.adjustSize()
        self.textbox_sold_animals_young_price = QLineEdit(windowMain)
        self.textbox_sold_animals_young_price.setGeometry(1000,570,50,40)
        self.textbox_sold_animals_young_price.setText("0")
        self.textbox_sold_animals_adult_price = QLineEdit(windowMain)
        self.textbox_sold_animals_adult_price.setGeometry(1060,570,50,40)
        self.textbox_sold_animals_adult_price.setText("0")
        self.textbox_sold_animals_old_price = QLineEdit(windowMain)
        self.textbox_sold_animals_old_price.setGeometry(1120,570,50,40)
        self.textbox_sold_animals_old_price.setText("0")
        self.label_feed_number = QLabel(windowMain)
        self.label_feed_number.setText('Количество корма \n (покупка)')
        self.label_feed_number.setFont(QFont("Times", 10, QFont.Bold))
        self.label_feed_number.move(750,630)
        self.label_feed_number.adjustSize()
        self.textbox_feed_number = QLineEdit(windowMain)
        self.textbox_feed_number.setGeometry(1000,630,120,40)
        self.textbox_feed_number.setText("0")
        self.label_feed_price = QLabel(windowMain)
        self.label_feed_price.setText('Цена корма \n (покупка)')
        self.label_feed_price.setFont(QFont("Times", 10, QFont.Bold))
        self.label_feed_price.move(750,690)
        self.label_feed_price.adjustSize()
        self.textbox_feed_price = QLineEdit(windowMain)
        self.textbox_feed_price.setGeometry(1000,690,120,40)
        self.textbox_feed_price.setText("0")
        self.label_forfeit = QLabel(windowMain)
        self.label_forfeit.setText('Неустойка')
        self.label_forfeit.setFont(QFont("Times", 10, QFont.Bold))
        self.label_forfeit.move(750,750)
        self.label_forfeit.adjustSize()
        self.textbox_forfeit = QLineEdit(windowMain)
        self.textbox_forfeit.setGeometry(1000,750,120,40)
        self.textbox_forfeit.setText("0")
        self.label_farm = QLabel(windowMain)
        self.label_farm.setText('Ферма')
        self.label_farm.setFont(QFont("Times", 12, QFont.Bold))
        self.label_farm.setGeometry(850,90,150,60)
        self.label_money_capital = QLabel(windowMain)
        self.label_money_capital.setText('Денежный капитал')
        self.label_money_capital.setFont(QFont("Times", 10, QFont.Bold))
        self.label_money_capital.move(750,160)
        self.label_money_capital.adjustSize()
        self.textbox_money_capital = QLineEdit(windowMain)
        self.textbox_money_capital.setGeometry(1000,160,120,40)
        self.textbox_money_capital.setText("0")
        self.label_total_capital = QLabel(windowMain)
        self.label_total_capital.setText('Общий капитал')
        self.label_total_capital.setFont(QFont("Times", 10, QFont.Bold))
        self.label_total_capital.move(750,220)
        self.label_total_capital.adjustSize()
        self.plain_total = QPlainTextEdit(windowMain)
        self.plain_total.setGeometry(1000,220,120,40)
        self.plain_total.setReadOnly(True)
        self.plain_total.setPlainText("0")
        self.label_animals = QLabel(windowMain)
        self.label_animals.setText('Животные на ферме')
        self.label_animals.setFont(QFont("Times", 10, QFont.Bold))
        self.label_animals.move(750,280)
        self.label_animals.adjustSize()
        self.textbox_animals_young = QLineEdit(windowMain)
        self.textbox_animals_young.setGeometry(1000,280,50,40)
        self.textbox_animals_young.setText("0")
        self.textbox_animals_adult = QLineEdit(windowMain)
        self.textbox_animals_adult.setGeometry(1060,280,50,40)
        self.textbox_animals_adult.setText("0")
        self.textbox_animals_old = QLineEdit(windowMain)
        self.textbox_animals_old.setGeometry(1120,280,50,40)
        self.textbox_animals_old.setText("0")
        self.label_feed = QLabel(windowMain)
        self.label_feed.setText('Корм в наличии')
        self.label_feed.setFont(QFont("Times", 10, QFont.Bold))
        self.label_feed.move(750,340)
        self.label_feed.adjustSize()
        self.textbox_feed = QLineEdit(windowMain)
        self.textbox_feed.setGeometry(1000,340,120,40)
        self.textbox_feed.setText("0")